package com.example.Bandproject.controllers;

import com.example.Bandproject.models.User;
import com.example.Bandproject.repositories.Repository;
import org.dom4j.rule.Mode;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;


@RestController // This means that this class is a Controller
@RequestMapping(path="/registration") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private Repository userRepository;


    @PostMapping // Map ONLY POST Requests
    public ModelAndView addNewUser (@RequestParam String firstName,
                                   @RequestParam String lastName,
                                   @RequestParam String username,
                                   @RequestParam String password,
                                   @RequestParam String instrument) {
        System.out.println("Something Happened");

        User n = new User();
        n.setFirstName(firstName);
        n.setLastName(lastName);
        n.setUsername(username);
        n.setPassword(password);
        n.setInstrument(instrument);
        userRepository.save(n);
        ModelAndView modelAndView = new ModelAndView("Success");
        return modelAndView;
    }
    @GetMapping
    public ModelAndView registrationPage(){
        ModelAndView modelAndView = new ModelAndView("registration");
        System.out.println("Something Happened in Get");
        return  modelAndView;
    }


    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

     
}